// Code generated by "stringer -type=PaletteType"; DO NOT EDIT.

package generator

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Monochromatic-1]
	_ = x[Greyscale-2]
	_ = x[Dynamic-3]
}

const _PaletteType_name = "UnknownMonochromaticGreyscaleDynamic"

var _PaletteType_index = [...]uint8{0, 7, 20, 29, 36}

func (i PaletteType) String() string {
	if i < 0 || i >= PaletteType(len(_PaletteType_index)-1) {
		return "PaletteType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PaletteType_name[_PaletteType_index[i]:_PaletteType_index[i+1]]
}
